@extends('layouts.app')
@section('title')
{{-- Title of insight here, generated by database --}}
@endsection
@section('description')
{{-- Possibly title + subtitle --}}
@endsection
@section('content')
@endsection
